from __future__ import annotations

from typing import Literal

DesktopLanguage = Literal["ru", "kk", "en"]

_TEXT: dict[DesktopLanguage, dict[str, str]] = {
    "ru": {
        "app_title": "GeoKZ — геологическое рабочее окно",
        "login_title": "Вход в GeoKZ",
        "server": "Сервер API",
        "username": "Пользователь",
        "password": "Пароль",
        "login": "Войти",
        "logout": "Выйти",
        "refresh": "Обновить",
        "update_all": "Обновить всё",
        "data_sources": "Источники данных",
        "field_review": "Проверка месторождений",
        "license_review": "Проверка лицензий",
        "provenance": "Provenance / аудит",
        "versions": "Версии",
        "application_version": "Приложение",
        "database_schema": "Схема БД",
        "bundled_core_dataset": "Встроенный Core Dataset",
        "installed_core_dataset": "Установленный Core Dataset",
        "provider_version": "Версия источника",
        "source_status": "Статус источника",
        "last_success": "Последняя успешная синхронизация",
        "last_error": "Последняя ошибка",
        "review_policy": "Решение о связи с источником не верифицирует геологический объект автоматически.",
        "raw_payload": "RAW payload",
        "normalized_payload": "Нормализованные данные",
        "comment": "Комментарий",
        "entity_id": "ID геологического объекта",
        "execute": "Выполнить",
        "accept": "Принять",
        "reject": "Отклонить",
        "audit_logs": "Журнал аудита",
        "load_audit": "Загрузить аудит",
        "role": "Роль",
        "session_user": "Пользователь",
        "not_available": "нет данных",
        "error": "Ошибка",
        "information": "Информация",
        "confirm_update_all": "Запустить синхронизацию всех зарегистрированных внешних источников?",
        "help_data_sources": "Экран показывает версии, состояние Core Dataset и статусы внешних источников. Внешний sync не подтверждает геологические факты.",
        "help_field_review": "Доступные действия приходят с backend как action descriptors. Клиент не вычисляет правила подтверждения самостоятельно.",
        "help_license_review": "ACCEPTED означает проверенную административную запись лицензии; это не создаёт геологический объект и не публикует факт.",
        "help_provenance": "AuditLog и revisions показывают кто, когда и почему изменил master data. Полный audit доступен администратору.",
    },
    "kk": {
        "app_title": "GeoKZ — геологиялық жұмыс терезесі",
        "login_title": "GeoKZ жүйесіне кіру",
        "server": "API сервері",
        "username": "Пайдаланушы",
        "password": "Құпиясөз",
        "login": "Кіру",
        "logout": "Шығу",
        "refresh": "Жаңарту",
        "update_all": "Барлығын жаңарту",
        "data_sources": "Дереккөздер",
        "field_review": "Кен орындарын тексеру",
        "license_review": "Лицензияларды тексеру",
        "provenance": "Provenance / аудит",
        "versions": "Нұсқалар",
        "application_version": "Қолданба",
        "database_schema": "ДҚ схемасы",
        "bundled_core_dataset": "Ішкі Core Dataset",
        "installed_core_dataset": "Орнатылған Core Dataset",
        "provider_version": "Дереккөз нұсқасы",
        "source_status": "Дереккөз күйі",
        "last_success": "Соңғы сәтті синхрондау",
        "last_error": "Соңғы қате",
        "review_policy": "Дереккөзбен байланысты растау геологиялық объектіні автоматты түрде верификацияламайды.",
        "raw_payload": "RAW payload",
        "normalized_payload": "Нормаланған деректер",
        "comment": "Түсініктеме",
        "entity_id": "Геологиялық объект ID",
        "execute": "Орындау",
        "accept": "Қабылдау",
        "reject": "Қабылдамау",
        "audit_logs": "Аудит журналы",
        "load_audit": "Аудитті жүктеу",
        "role": "Рөл",
        "session_user": "Пайдаланушы",
        "not_available": "дерек жоқ",
        "error": "Қате",
        "information": "Ақпарат",
        "confirm_update_all": "Тіркелген барлық сыртқы дереккөздерді синхрондауды іске қосу керек пе?",
        "help_data_sources": "Экран нұсқаларды, Core Dataset күйін және сыртқы дереккөз мәртебесін көрсетеді. Сыртқы sync геологиялық фактілерді растамайды.",
        "help_field_review": "Қолжетімді әрекеттер backend action descriptors арқылы келеді. Клиент растау ережелерін өзі есептемейді.",
        "help_license_review": "ACCEPTED тек лицензияның әкімшілік жазбасы тексерілгенін білдіреді; ол геологиялық объект немесе факт жасамайды.",
        "help_provenance": "AuditLog және revisions master data-ны кім, қашан және неге өзгерткенін көрсетеді. Толық audit әкімшіге қолжетімді.",
    },
    "en": {
        "app_title": "GeoKZ — geological workspace",
        "login_title": "Sign in to GeoKZ",
        "server": "API server",
        "username": "Username",
        "password": "Password",
        "login": "Sign in",
        "logout": "Sign out",
        "refresh": "Refresh",
        "update_all": "Update all",
        "data_sources": "Data sources",
        "field_review": "Field review",
        "license_review": "License review",
        "provenance": "Provenance / audit",
        "versions": "Versions",
        "application_version": "Application",
        "database_schema": "Database schema",
        "bundled_core_dataset": "Bundled Core Dataset",
        "installed_core_dataset": "Installed Core Dataset",
        "provider_version": "Provider version",
        "source_status": "Source status",
        "last_success": "Last successful sync",
        "last_error": "Last error",
        "review_policy": "Verifying a source link does not automatically verify the geological entity.",
        "raw_payload": "RAW payload",
        "normalized_payload": "Normalized data",
        "comment": "Comment",
        "entity_id": "Geological entity ID",
        "execute": "Execute",
        "accept": "Accept",
        "reject": "Reject",
        "audit_logs": "Audit log",
        "load_audit": "Load audit",
        "role": "Role",
        "session_user": "User",
        "not_available": "not available",
        "error": "Error",
        "information": "Information",
        "confirm_update_all": "Start synchronization for all registered external sources?",
        "help_data_sources": "This screen shows versions, Core Dataset state and external-source status. External synchronization never verifies geological facts.",
        "help_field_review": "Available actions come from backend action descriptors. The client does not reimplement review rules.",
        "help_license_review": "ACCEPTED only means an administrative license record was reviewed; it does not create a geological entity or publish a fact.",
        "help_provenance": "AuditLog and revisions show who changed master data, when and why. Full audit is available to administrators.",
    },
}


def text(language: DesktopLanguage, key: str) -> str:
    try:
        return _TEXT[language][key]
    except KeyError as error:
        raise KeyError(f"Missing desktop localization key {key!r} for {language}") from error


def localization_keys() -> dict[DesktopLanguage, frozenset[str]]:
    return {language: frozenset(values) for language, values in _TEXT.items()}
