from enum import StrEnum


class SyncMode(StrEnum):
    MANUAL = "MANUAL"
    AUTOMATIC = "AUTOMATIC"


class SyncRunStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class SyncBatchMode(StrEnum):
    MANUAL_ALL = "MANUAL_ALL"
    SCHEDULED_DUE = "SCHEDULED_DUE"


class SyncDispatchStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    ALREADY_RUNNING = "ALREADY_RUNNING"
    SKIPPED_NOT_DUE = "SKIPPED_NOT_DUE"
    SKIPPED_DISABLED = "SKIPPED_DISABLED"
    SKIPPED_MANUAL = "SKIPPED_MANUAL"
    SKIPPED_UNSUPPORTED = "SKIPPED_UNSUPPORTED"


class ExternalRecordStatus(StrEnum):
    STAGED = "STAGED"
    UNCHANGED = "UNCHANGED"
    CHANGED = "CHANGED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class EntityLinkStatus(StrEnum):
    AUTO_MATCHED = "AUTO_MATCHED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class MatchMethod(StrEnum):
    EXACT_ID = "EXACT_ID"
    EXACT_NAME = "EXACT_NAME"
    ALIAS = "ALIAS"
    SPATIAL = "SPATIAL"
    FUZZY = "FUZZY"
    MANUAL = "MANUAL"


class FieldReviewMatchStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    AMBIGUOUS = "AMBIGUOUS"
    UNMATCHED = "UNMATCHED"
    REVIEWER_LOCKED = "REVIEWER_LOCKED"
    UNAVAILABLE = "UNAVAILABLE"
    UNKNOWN = "UNKNOWN"


class FieldReviewActionCode(StrEnum):
    CONFIRM_LINK = "CONFIRM_LINK"
    REJECT_LINK = "REJECT_LINK"
    MANUAL_LINK = "MANUAL_LINK"
    CREATE_DRAFT_FIELD = "CREATE_DRAFT_FIELD"
